# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

markdown: kramdown
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
url:              http://localhost:4000
timezone:    America/New_York
pygments:    true

